/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package df_application.Panel;

import javax.swing.JLabel;

/**
 *
 * @author 362294
 */
public class Ressources extends javax.swing.JPanel {

    // GESTION DES VARIABLES
    enum mode_ecran {
        Nouveau, Modifier, Abandon, Sauveagerde, Rechercher
    };


    /**
     * Creates new form Assitance
     */
    public Ressources() {
        initComponents();

        JLabel lblNewLabel = new JLabel("Panel Assistance");
        lblNewLabel.setBounds(178, 109, 108, 14);
        this.add(lblNewLabel);

        this.setVisible(true);

        // gestion du mode de l'écran
        ManageEcran(mode_ecran.Rechercher);
    }

    private void ManageEcran(mode_ecran pMode) {
        switch (pMode) {
            case Abandon:
                edNom.setText("");
                edNom.setEnabled(false);
                edPrenom.setText("");
                edPrenom.setEnabled(false);
                edTJM.setText("");
                edTJM.setEnabled(false);
                edUID.setText("");
                edUID.setEnabled(false);
                //cbTypeContrat.setSelectedIndex(0);
                //cbTypeContrat.setEnabled(false);
                //jcbNomSociete.setSelectedItem(0);
                //jcbNomSociete.setEnabled(false);
                ManageEcran(mode_ecran.Rechercher);
                break;
            
            case Modifier:
                edNom.setText("");
                edNom.setEnabled(false);
                edPrenom.setText("");
                edPrenom.setEnabled(false);
                edTJM.setText("");
                edTJM.setEnabled(false);
                edUID.setText("");
                edUID.setEnabled(false);
                //cbTypeContrat.setSelectedIndex(0);
                //cbTypeContrat.setEnabled(false);
                //jcbNomSociete.setSelectedItem(0);
                //jcbNomSociete.setEnabled(false);
                break;

            case Nouveau:
                edNom.setText("");
                edNom.setEnabled(false);
                edPrenom.setText("");
                edPrenom.setEnabled(false);
                edTJM.setText("");
                edTJM.setEnabled(false);
                edUID.setText("");
                edUID.setEnabled(false);
                //cbTypeContrat.setSelectedIndex(0);
                //cbTypeContrat.setEnabled(false);
                //jcbNomSociete.setSelectedItem(0);
                //jcbNomSociete.setEnabled(false);
                break;
            case Rechercher:
                edNom.setText("");
                edNom.setEnabled(false);
                edPrenom.setText("");
                edPrenom.setEnabled(false);
                edTJM.setText("");
                edTJM.setEnabled(false);
                edUID.setText("");
                edUID.setEnabled(false);
                //cbTypeContrat.setSelectedIndex(0);
                //cbTypeContrat.setEnabled(false);
                //jcbNomSociete.setSelectedItem(0);
                //jcbNomSociete.setEnabled(false);
                break;
            case Sauveagerde:
                edNom.setText("");
                edNom.setEnabled(false);
                edPrenom.setText("");
                edPrenom.setEnabled(false);
                edTJM.setText("");
                edTJM.setEnabled(false);
                edUID.setText("");
                edUID.setEnabled(false);
                //cbTypeContrat.setSelectedIndex(0);
                //cbTypeContrat.setEnabled(false);
                //jcbNomSociete.setSelectedItem(0);
                //jcbNomSociete.setEnabled(false);
                break;
            default:
                break;

        }
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPaneDetail = new javax.swing.JPanel();
        jlUID = new javax.swing.JLabel();
        jlTJM = new javax.swing.JLabel();
        jlNom = new javax.swing.JLabel();
        edTJM = new javax.swing.JTextField();
        edUID = new javax.swing.JTextField();
        edNom = new javax.swing.JTextField();
        jlPrenom = new javax.swing.JLabel();
        edPrenom = new javax.swing.JTextField();
        cbTypeContrat = new javax.swing.JComboBox<>();
        jlNomSociete = new javax.swing.JLabel();
        jcbNomSociete = new javax.swing.JComboBox<>();
        jlContrat = new javax.swing.JLabel();
        jChBActif = new javax.swing.JCheckBox();
        btnNew = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        JPaneLList = new javax.swing.JPanel();
        jScrollPane_ListRessource = new javax.swing.JScrollPane();
        JtableListRessource = new javax.swing.JTable();

        jlUID.setText("UID");

        jlTJM.setText("TJM");

        jlNom.setText("Nom");

        edUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edUIDActionPerformed(evt);
            }
        });

        edNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNomActionPerformed(evt);
            }
        });

        jlPrenom.setText("Prénom");

        cbTypeContrat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlNomSociete.setText("Nom Societe");

        jcbNomSociete.setEditable(true);
        jcbNomSociete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbNomSociete.setToolTipText("");

        jlContrat.setText("Type de Contrat");

        jChBActif.setText("Actif");

        btnNew.setText("Nouveau");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnModify.setText("Modify");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPaneDetailLayout = new javax.swing.GroupLayout(JPaneDetail);
        JPaneDetail.setLayout(JPaneDetailLayout);
        JPaneDetailLayout.setHorizontalGroup(
            JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPaneDetailLayout.createSequentialGroup()
                        .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneDetailLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlContrat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTypeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNomSociete))
                            .addGroup(JPaneDetailLayout.createSequentialGroup()
                                .addComponent(jlUID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlNom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edUID)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(JPaneDetailLayout.createSequentialGroup()
                                .addComponent(jcbNomSociete, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlTJM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edTJM, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JPaneDetailLayout.createSequentialGroup()
                                .addComponent(jlPrenom)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edNom, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jChBActif))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPaneDetailLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave)
                        .addGap(8, 8, 8)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPaneDetailLayout.setVerticalGroup(
            JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneDetailLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUID)
                    .addComponent(jlNom)
                    .addComponent(edUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPrenom)
                    .addComponent(edPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChBActif))
                .addGap(18, 18, 18)
                .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlContrat)
                    .addComponent(cbTypeContrat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNomSociete)
                    .addComponent(jcbNomSociete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTJM)
                    .addComponent(edTJM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPaneDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew)
                    .addComponent(btnModify)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JtableListRessource.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_ListRessource.setViewportView(JtableListRessource);

        javax.swing.GroupLayout JPaneLListLayout = new javax.swing.GroupLayout(JPaneLList);
        JPaneLList.setLayout(JPaneLListLayout);
        JPaneLListLayout.setHorizontalGroup(
            JPaneLListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneLListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_ListRessource, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPaneLListLayout.setVerticalGroup(
            JPaneLListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPaneLListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_ListRessource, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JPaneDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPaneLList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPaneDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPaneLList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void edUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edUIDActionPerformed

    private void edNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNomActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        ManageEcran(mode_ecran.Nouveau);
    }//GEN-LAST:event_btnNewActionPerformed
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        ManageEcran(mode_ecran.Sauveagerde);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        ManageEcran(mode_ecran.Modifier);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        ManageEcran(mode_ecran.Abandon);
    }//GEN-LAST:event_btnCancelActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPaneDetail;
    private javax.swing.JPanel JPaneLList;
    private javax.swing.JTable JtableListRessource;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cbTypeContrat;
    private javax.swing.JTextField edNom;
    private javax.swing.JTextField edPrenom;
    private javax.swing.JTextField edTJM;
    private javax.swing.JTextField edUID;
    private javax.swing.JCheckBox jChBActif;
    private javax.swing.JScrollPane jScrollPane_ListRessource;
    private javax.swing.JComboBox<String> jcbNomSociete;
    private javax.swing.JLabel jlContrat;
    private javax.swing.JLabel jlNom;
    private javax.swing.JLabel jlNomSociete;
    private javax.swing.JLabel jlPrenom;
    private javax.swing.JLabel jlTJM;
    private javax.swing.JLabel jlUID;
    // End of variables declaration//GEN-END:variables

}
