/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package df_application;

import javax.swing.JLabel;

/**
 *
 * @author 362294
 */
public class DF_IFVisionGlobale extends javax.swing.JInternalFrame {


    
    static int openFrameCount = 0;
    static final int X_OFFSET = 30, Y_OFFSET = 30;

    /**
     * Creates new form Voiture
     */
    public DF_IFVisionGlobale() {

        // Configuration des bases 
        super("Digital Factory - VISION GLOBALE" + (++openFrameCount),
                true, //resizable
                true, //closable
               true, //maximizable
                true);//iconifiable
        initComponents();

        //setBounds(100, 100, 450, 300);
        //getContentPane().setLayout(null);
        setLocation(X_OFFSET * openFrameCount, Y_OFFSET * openFrameCount);


        /**
         * ***********************************************************************************
         * CONFIGURATION DE LA INTERNAL FRAME
        ************************************************************************************
         */
        JLabel lblNewLabel = new JLabel("Frame Voiture");
        lblNewLabel.setBounds(178, 109, 108, 14);
        getContentPane().add(lblNewLabel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainSplit = new javax.swing.JSplitPane();
        topSplit = new javax.swing.JSplitPane();
        voiture = new df_application.Panel.Voiture();
        commande = new df_application.Panel.Commande();
        bottomSplit = new javax.swing.JSplitPane();
        assitance = new df_application.Panel.Ressources();
        message = new df_application.Panel.Message();

        mainSplit.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainSplit.setName(""); // NOI18N

        topSplit.setLeftComponent(voiture);
        topSplit.setRightComponent(commande);

        mainSplit.setTopComponent(topSplit);

        assitance.setPreferredSize(new java.awt.Dimension(100, 200));
        bottomSplit.setRightComponent(assitance);
        bottomSplit.setLeftComponent(message);

        mainSplit.setRightComponent(bottomSplit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainSplit, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private df_application.Panel.Ressources assitance;
    private javax.swing.JSplitPane bottomSplit;
    private df_application.Panel.Commande commande;
    private javax.swing.JSplitPane mainSplit;
    private df_application.Panel.Message message;
    private javax.swing.JSplitPane topSplit;
    private df_application.Panel.Voiture voiture;
    // End of variables declaration//GEN-END:variables
}
